name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to staging server
        if: ${{ github.ref == 'refs/heads/stage' }}
        run: bash deploy.sh stage

      - name: Deploy to production server
        if: ${{ github.ref == 'refs/heads/master' }}
        run: bash deploy.sh master
